### ISSUE TITLE
Submit on last digit doesn't work

### ISSUE THREAD

**Issue by wolfcro1984** [halilozercan/ProgressButton#1]
When you type the last digit the onSubmit isn't invoked because of the error:
W/FlutterTextInput(17572): Unsupported operation: Cannot clear a fixed-length list

This is because you try to invoke 
`_pin.clear() `
in the clearTextFields method and dart doesn't allow it. 
I replaced it with
`_pin.forEach((e) => e = "");`
and not it works alright.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.14393], locale hr-HR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.26.1)
[√] VS Code, 64-bit edition (version 1.30.2)
[√] Connected device (1 available)

**Comment by halilozercan** [comment]
Are you sure you created this issue on the correct repository?

**Comment by wolfcro1984** [comment]
You're absolutely right. I apologize. I will close it now.
