### ISSUE TITLE
Button's 'child' content is shown during the 'InProgress' animation

### ISSUE THREAD

**Issue by mwgriffiths88** [halilozercan/ProgressButton#4]
The button shows it's `child` content instead of continuing with the `InProgress` animation. Here is an example in this state:

![in-progress-animation](https://user-images.githubusercontent.com/4941206/56196771-6114e700-602f-11e9-8454-33505764c8be.png)

The problem appears to relate too the snippet below. In this case, the animation will stop running after it's first completion:

https://github.com/halilozercan/ProgressButton/blob/5d4d39b1bc0cfd440623a293a1f6e9ae12ff62a8/lib/progress_button.dart#L106-L108

**Comment by mwgriffiths88** [comment]
#5

**Comment by kaoz70** [comment]
Hello, this fix is not published to [pub](https://pub.dev/packages/progress_button/versions)
